### ISSUE TITLE
Make the notification at 25 last forever?

### ISSUE THREAD

**Issue by urmyfaith** [t9tio/tomato-pie#4]
Should  be notified at 25 not only  25+5 mins.

First notice should be at 25.00,
Second notice should be at  25.00+5.00

**Comment by timqian** [comment]
at 25, tomato-pie do send a notification. but it will disappear after several seconds. The second notification will disappear only after user click it

**Comment by urmyfaith** [comment]
I did't saw the the notice at 25 all the day...

Maybe we should change the disappearance  approach to the second way.

**Comment by timqian** [comment]
I was thinking about it too. I guess you are using a external screen? The notification only appears at the native screen. I also occasionally miss alerts.

will look into it soon

**Comment by urmyfaith** [comment]
yes, we do have a  external screen.

**Comment by timqian** [comment]
FYI, If you are using a MacBook with an external screen like me. You can define where the notification to show, so you won't miss notifications.

![kapture 2019-03-01 at 10 39 05](https://user-images.githubusercontent.com/5512552/53612827-f9d1dd80-3c0e-11e9-9def-8388d61d2c9d.gif)

And about this feature. I am still considering if it is good because It will require user clicking notification too many times.

**Comment by timqian** [comment]
the fist notification won't auto disappear now
